version: "3.7"

services:
  # Volume cleanup service with Docker socket access
  db-cleanup:
    image: docker:cli
    command: >
      sh -c "
        docker volume rm -f redis_data postgres_data postgres_manager_data || true &&
        docker volume create --name=redis_data &&
        docker volume create --name=postgres_data &&
        docker volume create --name=postgres_manager_data
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: none 

  redis:
    restart: always
    container_name: redis
    image: redis:7.2.3-alpine
    volumes:
      - redis-data:/data
    depends_on:
      - db-cleanup

  postgres-data:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-data
    restart: always
    environment:
      POSTGRES_DB: ${DB_DASHBOARD_DBNAME}
      POSTGRES_USER: ${DB_DASHBOARD_USER}
      POSTGRES_PASSWORD: ${DB_DASHBOARD_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    depends_on:
      - db-cleanup

  postgres-manager:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-manager
    restart: always
    environment:
      POSTGRES_DB: ${DB_MANAGER_DBNAME}
      POSTGRES_USER: ${DB_MANAGER_USER}
      POSTGRES_PASSWORD: ${DB_MANAGER_PASSWORD}
    volumes:
      - postgres-manager-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      - db-cleanup

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "8889:80"
    volumes:
      - ./db-data/pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: br_dashboard
    external: true

volumes:
  redis-data:
    name: redis_data
  postgres-data:
    name: postgres_data
  postgres-manager-data:
    name: postgres_manager_data